apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: devopsRoot
            - name: MYSQL_USER
              value: devops
            - name: MYSQL_PASSWORD
              value: devops
            - name: MYSQL_DATABASE
              value: devops
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            limits:
              cpu: 750m
              memory: 900Mi
            requests:
              cpu: 750m
              memory: 900Mi
